DROP TABLE product_catalog;
CREATE TABLE product_catalog(name TEXT);

-- https://en.wikipedia.org/wiki/List_of_culinary_fruits
INSERT INTO product_catalog(name) VALUES('Abiu');
INSERT INTO product_catalog(name) VALUES('Açaí');
INSERT INTO product_catalog(name) VALUES('Acerola');
INSERT INTO product_catalog(name) VALUES('Ackee');
INSERT INTO product_catalog(name) VALUES('African cherry orange');
INSERT INTO product_catalog(name) VALUES('African mango');
INSERT INTO product_catalog(name) VALUES('African moringa');
INSERT INTO product_catalog(name) VALUES('Ambarella');
INSERT INTO product_catalog(name) VALUES('American Black Elderberry');
INSERT INTO product_catalog(name) VALUES('American Chestnut');
INSERT INTO product_catalog(name) VALUES('grape');
INSERT INTO product_catalog(name) VALUES('American Hazelnut');
INSERT INTO product_catalog(name) VALUES('American Pawpaw');
INSERT INTO product_catalog(name) VALUES('American persimmon');
INSERT INTO product_catalog(name) VALUES('American plum');
INSERT INTO product_catalog(name) VALUES('American Red Elderberry');
INSERT INTO product_catalog(name) VALUES('American Red Raspberry');
INSERT INTO product_catalog(name) VALUES('Annona');
INSERT INTO product_catalog(name) VALUES('Apple');
INSERT INTO product_catalog(name) VALUES('Malay apple');
INSERT INTO product_catalog(name) VALUES('Custard apple');
INSERT INTO product_catalog(name) VALUES('Elephant apple');
INSERT INTO product_catalog(name) VALUES('key apple');
INSERT INTO product_catalog(name) VALUES('mammee apple');
INSERT INTO product_catalog(name) VALUES('Apricot');
INSERT INTO product_catalog(name) VALUES('Araza');
INSERT INTO product_catalog(name) VALUES('Arhat');
INSERT INTO product_catalog(name) VALUES('Atemoya');
INSERT INTO product_catalog(name) VALUES('Atherton Raspberry');
INSERT INTO product_catalog(name) VALUES('Avocado');

INSERT INTO product_catalog(name) VALUES('Babaco');
INSERT INTO product_catalog(name) VALUES('Bacupari');
INSERT INTO product_catalog(name) VALUES('Bacuri');
INSERT INTO product_catalog(name) VALUES('Bael');
INSERT INTO product_catalog(name) VALUES('Banana');
INSERT INTO product_catalog(name) VALUES('Barbadine');
INSERT INTO product_catalog(name) VALUES('acerola');
INSERT INTO product_catalog(name) VALUES('Batuan');
INSERT INTO product_catalog(name) VALUES('Beach Plum');
INSERT INTO product_catalog(name) VALUES('Bearberry');
INSERT INTO product_catalog(name) VALUES('Betel Nut');
INSERT INTO product_catalog(name) VALUES('Bignay');
INSERT INTO product_catalog(name) VALUES('Bilberry');
INSERT INTO product_catalog(name) VALUES('Bilimbi');
INSERT INTO product_catalog(name) VALUES('Biriba');
INSERT INTO product_catalog(name) VALUES('Bitter melon');
INSERT INTO product_catalog(name) VALUES('Black Apple');
INSERT INTO product_catalog(name) VALUES('Black cherry');
INSERT INTO product_catalog(name) VALUES('Black raspberry');
INSERT INTO product_catalog(name) VALUES('Black Mulberry');
INSERT INTO product_catalog(name) VALUES('Black Sapote');
INSERT INTO product_catalog(name) VALUES('Black Walnut');
INSERT INTO product_catalog(name) VALUES('Blackberry');
INSERT INTO product_catalog(name) VALUES('Blood Orange');
INSERT INTO product_catalog(name) VALUES('Blue tongue');
INSERT INTO product_catalog(name) VALUES('Blueberry');
INSERT INTO product_catalog(name) VALUES('Bolivian coconut');
INSERT INTO product_catalog(name) VALUES('Bolwarra');
INSERT INTO product_catalog(name) VALUES('Boquila');
INSERT INTO product_catalog(name) VALUES('Bottle Gourd');
INSERT INTO product_catalog(name) VALUES('Brazilian Guava');
INSERT INTO product_catalog(name) VALUES('Breadnut');
INSERT INTO product_catalog(name) VALUES('Mayan breadnut');
INSERT INTO product_catalog(name) VALUES('Broad-leaf Bramble');
INSERT INTO product_catalog(name) VALUES('Brazilian Guava');
INSERT INTO product_catalog(name) VALUES('Brush cherry');
INSERT INTO product_catalog(name) VALUES('Buddha''s Hand');
INSERT INTO product_catalog(name) VALUES('Buffaloberry');
INSERT INTO product_catalog(name) VALUES('Burdekin Plum');
INSERT INTO product_catalog(name) VALUES('Burmese grape');
INSERT INTO product_catalog(name) VALUES('Bush tomato');
INSERT INTO product_catalog(name) VALUES('Button Mangosteen');

INSERT INTO product_catalog(name) VALUES('Caimito');
INSERT INTO product_catalog(name) VALUES('Calabash Tree');
INSERT INTO product_catalog(name) VALUES('Calamondin');
INSERT INTO product_catalog(name) VALUES('Calamansi');
INSERT INTO product_catalog(name) VALUES('CamuCamu');
INSERT INTO product_catalog(name) VALUES('Canary melon');
INSERT INTO product_catalog(name) VALUES('Canistel');
INSERT INTO product_catalog(name) VALUES('Cantaloupe');
INSERT INTO product_catalog(name) VALUES('Cape Gooseberry');
INSERT INTO product_catalog(name) VALUES('Capuli cherry');
INSERT INTO product_catalog(name) VALUES('Carambola');
INSERT INTO product_catalog(name) VALUES('Cardón');
INSERT INTO product_catalog(name) VALUES('Ceratonia siliqua');
INSERT INTO product_catalog(name) VALUES('Cashew apple');
INSERT INTO product_catalog(name) VALUES('Cassabanana');
INSERT INTO product_catalog(name) VALUES('Cattley Guava');
INSERT INTO product_catalog(name) VALUES('Cawesh');
INSERT INTO product_catalog(name) VALUES('Cedar Bay cherry');
INSERT INTO product_catalog(name) VALUES('Ceriman');
INSERT INTO product_catalog(name) VALUES('Cereus peruvianus');
INSERT INTO product_catalog(name) VALUES('Dovyalis hebecarpa');
INSERT INTO product_catalog(name) VALUES('Charichuelo');
INSERT INTO product_catalog(name) VALUES('Chayote');
INSERT INTO product_catalog(name) VALUES('Moraceae');
INSERT INTO product_catalog(name) VALUES('Chempedak');
INSERT INTO product_catalog(name) VALUES('Chenet');
INSERT INTO product_catalog(name) VALUES('Cherimoya');
INSERT INTO product_catalog(name) VALUES('Cherry');
INSERT INTO product_catalog(name) VALUES('Cherry ballart');
INSERT INTO product_catalog(name) VALUES('Cherry of the Rio Grande');
INSERT INTO product_catalog(name) VALUES('Chilean guava');
INSERT INTO product_catalog(name) VALUES('Chinese jujube');
INSERT INTO product_catalog(name) VALUES('Chinese Olive');
INSERT INTO product_catalog(name) VALUES('Chinese Quince');
INSERT INTO product_catalog(name) VALUES('Chokeberry');
INSERT INTO product_catalog(name) VALUES('Chokecherry');
INSERT INTO product_catalog(name) VALUES('Chupa-Chupa');
INSERT INTO product_catalog(name) VALUES('Citron');
INSERT INTO product_catalog(name) VALUES('Clementine');
INSERT INTO product_catalog(name) VALUES('Cloudberry');
INSERT INTO product_catalog(name) VALUES('Cluster fig');
INSERT INTO product_catalog(name) VALUES('Cocky apple');
INSERT INTO product_catalog(name) VALUES('Coco Plum');
INSERT INTO product_catalog(name) VALUES('Cocona');
INSERT INTO product_catalog(name) VALUES('Coconut');
INSERT INTO product_catalog(name) VALUES('Cocoplum');
INSERT INTO product_catalog(name) VALUES('Coffee');
INSERT INTO product_catalog(name) VALUES('Cola nut');
INSERT INTO product_catalog(name) VALUES('Common apple-berry');
INSERT INTO product_catalog(name) VALUES('Conkerberry');
INSERT INTO product_catalog(name) VALUES('Cornelian cherry');
INSERT INTO product_catalog(name) VALUES('Costa Rican Guava');
INSERT INTO product_catalog(name) VALUES('Cranberry');
INSERT INTO product_catalog(name) VALUES('Crowberry');
INSERT INTO product_catalog(name) VALUES('Cupuaçu');
INSERT INTO product_catalog(name) VALUES('Currant');
INSERT INTO product_catalog(name) VALUES('Curry-leaf Tree');
INSERT INTO product_catalog(name) VALUES('Custard Apple');

INSERT INTO product_catalog(name) VALUES('Dabai');
INSERT INTO product_catalog(name) VALUES('Damson plum');
INSERT INTO product_catalog(name) VALUES('Date');
INSERT INTO product_catalog(name) VALUES('Date plum');
INSERT INTO product_catalog(name) VALUES('Davidson''s plum');
INSERT INTO product_catalog(name) VALUES('Dead Man''s Fingers');
INSERT INTO product_catalog(name) VALUES('Desert banana');
INSERT INTO product_catalog(name) VALUES('Desert fig');
INSERT INTO product_catalog(name) VALUES('Desert lime');
INSERT INTO product_catalog(name) VALUES('Dodder laurel');
INSERT INTO product_catalog(name) VALUES('Doubah');
INSERT INTO product_catalog(name) VALUES('Double Coconut');
INSERT INTO product_catalog(name) VALUES('Dragonfruit');
INSERT INTO product_catalog(name) VALUES('Duku');
INSERT INTO product_catalog(name) VALUES('Durian');

INSERT INTO product_catalog(name) VALUES('Eastern May Hawthorn');
INSERT INTO product_catalog(name) VALUES('Elderberry');
INSERT INTO product_catalog(name) VALUES('Elephant Apple');
INSERT INTO product_catalog(name) VALUES('Indian gooseberry');
INSERT INTO product_catalog(name) VALUES('Emu Apple');
INSERT INTO product_catalog(name) VALUES('Emu berry');

INSERT INTO product_catalog(name) VALUES('Falberry');
INSERT INTO product_catalog(name) VALUES('False-mastic');
INSERT INTO product_catalog(name) VALUES('Feijoa');
INSERT INTO product_catalog(name) VALUES('Fibrous Satinash');
INSERT INTO product_catalog(name) VALUES('Fig');
INSERT INTO product_catalog(name) VALUES('Finger Lime');
INSERT INTO product_catalog(name) VALUES('Florida strangler fig');
INSERT INTO product_catalog(name) VALUES('Forest strawberries');

INSERT INTO product_catalog(name) VALUES('Gac');
INSERT INTO product_catalog(name) VALUES('Galia melon');
INSERT INTO product_catalog(name) VALUES('Gambooge');
INSERT INTO product_catalog(name) VALUES('Genip');
INSERT INTO product_catalog(name) VALUES('Colombia');
INSERT INTO product_catalog(name) VALUES('Giant Granadilla');
INSERT INTO product_catalog(name) VALUES('Gooseberry');
INSERT INTO product_catalog(name) VALUES('Ceylon gooseberry');
INSERT INTO product_catalog(name) VALUES('Indian gooseberry');
INSERT INTO product_catalog(name) VALUES('Otaheite gooseberry');
INSERT INTO product_catalog(name) VALUES('cape gooseberry');
INSERT INTO product_catalog(name) VALUES('Goumi');
INSERT INTO product_catalog(name) VALUES('Governor’s Plum');
INSERT INTO product_catalog(name) VALUES('Montessa granadilla');
INSERT INTO product_catalog(name) VALUES('yellow granadilla');
INSERT INTO product_catalog(name) VALUES('Grape');
INSERT INTO product_catalog(name) VALUES('Grapefruit');
INSERT INTO product_catalog(name) VALUES('Greengage');
INSERT INTO product_catalog(name) VALUES('Ground Plum');
INSERT INTO product_catalog(name) VALUES('Grumichama');
INSERT INTO product_catalog(name) VALUES('Guanabana');
INSERT INTO product_catalog(name) VALUES('Guarana');
INSERT INTO product_catalog(name) VALUES('Guava');
INSERT INTO product_catalog(name) VALUES('Cattley guava');
INSERT INTO product_catalog(name) VALUES('Chilean guava');
INSERT INTO product_catalog(name) VALUES('Costa Rican guava');
INSERT INTO product_catalog(name) VALUES('pineapple guava');
INSERT INTO product_catalog(name) VALUES('purple guava');
INSERT INTO product_catalog(name) VALUES('strawberry guava');
INSERT INTO product_catalog(name) VALUES('Guavaberry');

INSERT INTO product_catalog(name) VALUES('Hackberry');
INSERT INTO product_catalog(name) VALUES('Hairless rambutan');
INSERT INTO product_catalog(name) VALUES('Hardy Kiwi');
INSERT INTO product_catalog(name) VALUES('Crataegus');
INSERT INTO product_catalog(name) VALUES('Hog Plum');
INSERT INTO product_catalog(name) VALUES('Honeydew');
INSERT INTO product_catalog(name) VALUES(' Edible honeysuckle');
INSERT INTO product_catalog(name) VALUES('Horned melon');
INSERT INTO product_catalog(name) VALUES('Huckleberry');
INSERT INTO product_catalog(name) VALUES('Huito');

INSERT INTO product_catalog(name) VALUES('Ice Cream Bean');
INSERT INTO product_catalog(name) VALUES('Ilama');
INSERT INTO product_catalog(name) VALUES('Illawarra Plum');
INSERT INTO product_catalog(name) VALUES('Imbe');
INSERT INTO product_catalog(name) VALUES('Indian almond');
INSERT INTO product_catalog(name) VALUES('Indian gooseberry');
INSERT INTO product_catalog(name) VALUES('Indian jujube');
INSERT INTO product_catalog(name) VALUES('Indian prune');

INSERT INTO product_catalog(name) VALUES('Jabuticaba');
INSERT INTO product_catalog(name) VALUES('Jackfruit');
INSERT INTO product_catalog(name) VALUES('Jambul');
INSERT INTO product_catalog(name) VALUES('Japanese Persimmon');
INSERT INTO product_catalog(name) VALUES('Jatobá');
INSERT INTO product_catalog(name) VALUES('Jelly Palm');
INSERT INTO product_catalog(name) VALUES('Jocote');
INSERT INTO product_catalog(name) VALUES('Jujube');
INSERT INTO product_catalog(name) VALUES('Chinese jujube');
INSERT INTO product_catalog(name) VALUES('Indian jujube');
INSERT INTO product_catalog(name) VALUES('Juniper berry');

INSERT INTO product_catalog(name) VALUES('Kabosu');
INSERT INTO product_catalog(name) VALUES('Kaffir lime');
INSERT INTO product_catalog(name) VALUES('Kahikatea');
INSERT INTO product_catalog(name) VALUES('Kakadu lime');
INSERT INTO product_catalog(name) VALUES('Kakadu plum');
INSERT INTO product_catalog(name) VALUES('Kandis');
INSERT INTO product_catalog(name) VALUES('Kapok');
INSERT INTO product_catalog(name) VALUES('Karkalla');
INSERT INTO product_catalog(name) VALUES('Karonda');
INSERT INTO product_catalog(name) VALUES('Kei apple');
INSERT INTO product_catalog(name) VALUES('Kepel fruit');
INSERT INTO product_catalog(name) VALUES('Keule');
INSERT INTO product_catalog(name) VALUES('Key Lime');
INSERT INTO product_catalog(name) VALUES('Kitembilla');
INSERT INTO product_catalog(name) VALUES('horned melon');
INSERT INTO product_catalog(name) VALUES('Kiwifruit');
INSERT INTO product_catalog(name) VALUES('Korlan');
INSERT INTO product_catalog(name) VALUES('Kumquat');
INSERT INTO product_catalog(name) VALUES('meiwa kumquat');
INSERT INTO product_catalog(name) VALUES('nagami kumquat');
INSERT INTO product_catalog(name) VALUES('Kundong');
INSERT INTO product_catalog(name) VALUES('Kutjera');
INSERT INTO product_catalog(name) VALUES('Kwai Muk');

INSERT INTO product_catalog(name) VALUES('Lady apple');
INSERT INTO product_catalog(name) VALUES('Lakoocha');
INSERT INTO product_catalog(name) VALUES('Langsat');
INSERT INTO product_catalog(name) VALUES('Lanzones');
INSERT INTO product_catalog(name) VALUES('Lapsi');
INSERT INTO product_catalog(name) VALUES('Lardizabala');
INSERT INTO product_catalog(name) VALUES('Lemon');
INSERT INTO product_catalog(name) VALUES('Lemon aspen');
INSERT INTO product_catalog(name) VALUES('Leucaena');
INSERT INTO product_catalog(name) VALUES('Lillypilly');
INSERT INTO product_catalog(name) VALUES('Little gooseberry tree');
INSERT INTO product_catalog(name) VALUES('Lime');
INSERT INTO product_catalog(name) VALUES('Limeberry');
INSERT INTO product_catalog(name) VALUES('Limequat');
INSERT INTO product_catalog(name) VALUES('Lingonberry');
INSERT INTO product_catalog(name) VALUES('Loganberry');
INSERT INTO product_catalog(name) VALUES('Longan');
INSERT INTO product_catalog(name) VALUES('Loquat');
INSERT INTO product_catalog(name) VALUES('Louvi');
INSERT INTO product_catalog(name) VALUES('Lúcuma');
INSERT INTO product_catalog(name) VALUES('Lychee');

INSERT INTO product_catalog(name) VALUES('Ma-praang');
INSERT INTO product_catalog(name) VALUES('Mabolo');
INSERT INTO product_catalog(name) VALUES('Macadamia');
INSERT INTO product_catalog(name) VALUES('rough shell macadamia');
INSERT INTO product_catalog(name) VALUES('Madrono');
INSERT INTO product_catalog(name) VALUES('Malabar plum');
INSERT INTO product_catalog(name) VALUES('Malay Apple');
INSERT INTO product_catalog(name) VALUES('Mamey Sapote');
INSERT INTO product_catalog(name) VALUES('Mammee Apple');
INSERT INTO product_catalog(name) VALUES('Mamoncillo');
INSERT INTO product_catalog(name) VALUES('Mandarin');
INSERT INTO product_catalog(name) VALUES('Mangaba');
INSERT INTO product_catalog(name) VALUES('Mango');
INSERT INTO product_catalog(name) VALUES('Mangosteen');
INSERT INTO product_catalog(name) VALUES('Manila tamarind');
INSERT INTO product_catalog(name) VALUES('Manoao');
INSERT INTO product_catalog(name) VALUES('Maqui');
INSERT INTO product_catalog(name) VALUES('Marang');
INSERT INTO product_catalog(name) VALUES('Marula');
INSERT INTO product_catalog(name) VALUES('Breadnut, Mayan');
INSERT INTO product_catalog(name) VALUES('Mayapple');
INSERT INTO product_catalog(name) VALUES('Eastern may hawthorn');
INSERT INTO product_catalog(name) VALUES('Maypop');
INSERT INTO product_catalog(name) VALUES('Medlar');
INSERT INTO product_catalog(name) VALUES('Meiwa Kumquat');
INSERT INTO product_catalog(name) VALUES('Melinjo');
INSERT INTO product_catalog(name) VALUES('Melon pear');
INSERT INTO product_catalog(name) VALUES('Midyim');
INSERT INTO product_catalog(name) VALUES('Miracle Fruit');
INSERT INTO product_catalog(name) VALUES('Mock Strawberry');
INSERT INTO product_catalog(name) VALUES('purple mombin');
INSERT INTO product_catalog(name) VALUES('red mombin');
INSERT INTO product_catalog(name) VALUES('yellow mombin');
INSERT INTO product_catalog(name) VALUES('Monkey Jackfruit');
INSERT INTO product_catalog(name) VALUES('Monkey Tamarind');
INSERT INTO product_catalog(name) VALUES('Monstera');
INSERT INTO product_catalog(name) VALUES('Montessa Granadilla');
INSERT INTO product_catalog(name) VALUES('Mora Común');
INSERT INTO product_catalog(name) VALUES('Mora de Castilla');
INSERT INTO product_catalog(name) VALUES('Morinda');
INSERT INTO product_catalog(name) VALUES('Morinda citrifolia');
INSERT INTO product_catalog(name) VALUES('Mortiño');
INSERT INTO product_catalog(name) VALUES('Mountain pepper');
INSERT INTO product_catalog(name) VALUES('Mountain Soursop');
INSERT INTO product_catalog(name) VALUES('Mulberry');
INSERT INTO product_catalog(name) VALUES('wild plum');
INSERT INTO product_catalog(name) VALUES('Mundu');
INSERT INTO product_catalog(name) VALUES('Muntries');
INSERT INTO product_catalog(name) VALUES('Muscadine');
INSERT INTO product_catalog(name) VALUES('Muskmelon');

INSERT INTO product_catalog(name) VALUES('Naartjie');
INSERT INTO product_catalog(name) VALUES('Nagami Kumquat');
INSERT INTO product_catalog(name) VALUES('Nageia');
INSERT INTO product_catalog(name) VALUES('Nance');
INSERT INTO product_catalog(name) VALUES('Nannyberry');
INSERT INTO product_catalog(name) VALUES('Naranjilla');
INSERT INTO product_catalog(name) VALUES('Native currant');
INSERT INTO product_catalog(name) VALUES('Native gooseberry');
INSERT INTO product_catalog(name) VALUES('Native raspberry');
INSERT INTO product_catalog(name) VALUES('peach');
INSERT INTO product_catalog(name) VALUES('Neem');
INSERT INTO product_catalog(name) VALUES('Néré');
INSERT INTO product_catalog(name) VALUES('Nonda plum');
INSERT INTO product_catalog(name) VALUES('Noni');
INSERT INTO product_catalog(name) VALUES('Nungu');
INSERT INTO product_catalog(name) VALUES('Nutmeg');

INSERT INTO product_catalog(name) VALUES('Oil Palm');
INSERT INTO product_catalog(name) VALUES('Olive');
INSERT INTO product_catalog(name) VALUES('Orange');
INSERT INTO product_catalog(name) VALUES('Oregon grape');
INSERT INTO product_catalog(name) VALUES('Oroblanco');
INSERT INTO product_catalog(name) VALUES('Otaheite gooseberry');
INSERT INTO product_catalog(name) VALUES('Palmyra Palm');
INSERT INTO product_catalog(name) VALUES('Papaya');
INSERT INTO product_catalog(name) VALUES('Passion fruit');
INSERT INTO product_catalog(name) VALUES('Pawpaw');
INSERT INTO product_catalog(name) VALUES('Peach');
INSERT INTO product_catalog(name) VALUES('Peach palm');
INSERT INTO product_catalog(name) VALUES('Peanut');
INSERT INTO product_catalog(name) VALUES('Peanut butter fruit');
INSERT INTO product_catalog(name) VALUES('Pear');
INSERT INTO product_catalog(name) VALUES('Pecan');
INSERT INTO product_catalog(name) VALUES('Pepino');
INSERT INTO product_catalog(name) VALUES('Pequi');
INSERT INTO product_catalog(name) VALUES('Persian lime');
INSERT INTO product_catalog(name) VALUES('American persimmon');
INSERT INTO product_catalog(name) VALUES('Oriental persimmon');
INSERT INTO product_catalog(name) VALUES('Peumo');
INSERT INTO product_catalog(name) VALUES('Phalsa');
INSERT INTO product_catalog(name) VALUES('Pigeon pea');
INSERT INTO product_catalog(name) VALUES('Pigeon plum');
INSERT INTO product_catalog(name) VALUES('Pigface');
INSERT INTO product_catalog(name) VALUES('Pili Nut');
INSERT INTO product_catalog(name) VALUES('Pindo Palm');
INSERT INTO product_catalog(name) VALUES('Pineapple');
INSERT INTO product_catalog(name) VALUES('Pineapple guava');
INSERT INTO product_catalog(name) VALUES('Pink-flowered Native Raspberry');
INSERT INTO product_catalog(name) VALUES('Pistachio');
INSERT INTO product_catalog(name) VALUES('Dragon fruit');
INSERT INTO product_catalog(name) VALUES('Pitomba');
INSERT INTO product_catalog(name) VALUES('Plum');
INSERT INTO product_catalog(name) VALUES('Pois doux');
INSERT INTO product_catalog(name) VALUES('Pomegranate');
INSERT INTO product_catalog(name) VALUES('Pomelo');
INSERT INTO product_catalog(name) VALUES('Pommecythère');
INSERT INTO product_catalog(name) VALUES('Pommerac');
INSERT INTO product_catalog(name) VALUES('Annona glabra');
INSERT INTO product_catalog(name) VALUES('Prickly pear');
INSERT INTO product_catalog(name) VALUES('Pulasan');
INSERT INTO product_catalog(name) VALUES('Pummelo');
INSERT INTO product_catalog(name) VALUES('Pumpkin');
INSERT INTO product_catalog(name) VALUES('Pupunha');
INSERT INTO product_catalog(name) VALUES('Purple apple-berry');
INSERT INTO product_catalog(name) VALUES('Purple granadilla');
INSERT INTO product_catalog(name) VALUES('Purple Guava');
INSERT INTO product_catalog(name) VALUES('Purple Mombin');

INSERT INTO product_catalog(name) VALUES('Quandong');
INSERT INTO product_catalog(name) VALUES('Queensland Ebony');
INSERT INTO product_catalog(name) VALUES('Quince');

INSERT INTO product_catalog(name) VALUES('Raisin tree');
INSERT INTO product_catalog(name) VALUES('Rambutan');
INSERT INTO product_catalog(name) VALUES('Raspberry');
INSERT INTO product_catalog(name) VALUES('Red granadilla');
INSERT INTO product_catalog(name) VALUES('Red Mombin');
INSERT INTO product_catalog(name) VALUES('Red Mulberry');
INSERT INTO product_catalog(name) VALUES('Rhubarb');
INSERT INTO product_catalog(name) VALUES('Riberry');
INSERT INTO product_catalog(name) VALUES('Rimu');
INSERT INTO product_catalog(name) VALUES('Rollinia');
INSERT INTO product_catalog(name) VALUES('Rose apple');
INSERT INTO product_catalog(name) VALUES('Rose hip');
INSERT INTO product_catalog(name) VALUES('Rose-leaf Bramble');
INSERT INTO product_catalog(name) VALUES('Rose myrtle');
INSERT INTO product_catalog(name) VALUES('Rough Shell Macadamia');
INSERT INTO product_catalog(name) VALUES('Rowan');

INSERT INTO product_catalog(name) VALUES('Safou');
INSERT INTO product_catalog(name) VALUES('Sageretia');
INSERT INTO product_catalog(name) VALUES('Saguaro');
INSERT INTO product_catalog(name) VALUES('Salak');
INSERT INTO product_catalog(name) VALUES('Salal');
INSERT INTO product_catalog(name) VALUES('Salmonberry');
INSERT INTO product_catalog(name) VALUES('Sandpaper Fig');
INSERT INTO product_catalog(name) VALUES('Santol');
INSERT INTO product_catalog(name) VALUES('mamey');
INSERT INTO product_catalog(name) VALUES('Sapodilla');
INSERT INTO product_catalog(name) VALUES('#fibrous_satinash#fibrous satinash');
INSERT INTO product_catalog(name) VALUES('Saskatoonberry');
INSERT INTO product_catalog(name) VALUES('Saw Palmetto');
INSERT INTO product_catalog(name) VALUES('Sea-buckthorn');
INSERT INTO product_catalog(name) VALUES('Sea Grape');
INSERT INTO product_catalog(name) VALUES('Serviceberry');
INSERT INTO product_catalog(name) VALUES('Shipova');
INSERT INTO product_catalog(name) VALUES('Sloe');
INSERT INTO product_catalog(name) VALUES('Small-leaf tamarind');
INSERT INTO product_catalog(name) VALUES('Snow berry');
INSERT INTO product_catalog(name) VALUES('Soncoya');
INSERT INTO product_catalog(name) VALUES('Service tree');
INSERT INTO product_catalog(name) VALUES('Soursop');
INSERT INTO product_catalog(name) VALUES('Southern Crabapple');
INSERT INTO product_catalog(name) VALUES('Spanish lime');
INSERT INTO product_catalog(name) VALUES('Spanish tamarind');
INSERT INTO product_catalog(name) VALUES('Spiny Monkey-orange');
INSERT INTO product_catalog(name) VALUES('Star Apple');
INSERT INTO product_catalog(name) VALUES('carambola');
INSERT INTO product_catalog(name) VALUES('Strawberry');
INSERT INTO product_catalog(name) VALUES('Strawberry Guava');
INSERT INTO product_catalog(name) VALUES('ugni');
INSERT INTO product_catalog(name) VALUES('Strawberry Pear');
INSERT INTO product_catalog(name) VALUES('Sugar Apple');
INSERT INTO product_catalog(name) VALUES('Surinam Cherry');
INSERT INTO product_catalog(name) VALUES('Sweet apple-berry');
INSERT INTO product_catalog(name) VALUES('Sweet Granadilla');
INSERT INTO product_catalog(name) VALUES('Sweet Lemon');
INSERT INTO product_catalog(name) VALUES('Sweet orange');
INSERT INTO product_catalog(name) VALUES('Sweet pepper');
INSERT INTO product_catalog(name) VALUES('Sweetsop');
INSERT INTO product_catalog(name) VALUES('Sycamore fig');

INSERT INTO product_catalog(name) VALUES('Tahitian apple');
INSERT INTO product_catalog(name) VALUES('Tamarillo');
INSERT INTO product_catalog(name) VALUES('Tamarind');
INSERT INTO product_catalog(name) VALUES('Manila tamarind');
INSERT INTO product_catalog(name) VALUES('monkey tamarind');
INSERT INTO product_catalog(name) VALUES('velvet tamarind');
INSERT INTO product_catalog(name) VALUES('Tangerine');
INSERT INTO product_catalog(name) VALUES('Tanjong');
INSERT INTO product_catalog(name) VALUES('Texas Persimmon');
INSERT INTO product_catalog(name) VALUES('Thimbleberry');
INSERT INTO product_catalog(name) VALUES('T?tara');
INSERT INTO product_catalog(name) VALUES('Toyon');
INSERT INTO product_catalog(name) VALUES('Tropical Almond');

INSERT INTO product_catalog(name) VALUES('Ugni');

INSERT INTO product_catalog(name) VALUES('Vanilla');
INSERT INTO product_catalog(name) VALUES('Velvet Tamarind');

INSERT INTO product_catalog(name) VALUES('Wampee');
INSERT INTO product_catalog(name) VALUES('Wani');
INSERT INTO product_catalog(name) VALUES('Water Apple');
INSERT INTO product_catalog(name) VALUES('Watermelon');
INSERT INTO product_catalog(name) VALUES('Wax apple');
INSERT INTO product_catalog(name) VALUES('Wax Gourd');
INSERT INTO product_catalog(name) VALUES('Wax jambu');
INSERT INTO product_catalog(name) VALUES('acerola');
INSERT INTO product_catalog(name) VALUES('White aspen');
INSERT INTO product_catalog(name) VALUES('White Mulberry');
INSERT INTO product_catalog(name) VALUES('White Sapote');
INSERT INTO product_catalog(name) VALUES('bilberry');
INSERT INTO product_catalog(name) VALUES('Wild grape');
INSERT INTO product_catalog(name) VALUES('Wild orange');
INSERT INTO product_catalog(name) VALUES('Wild peach');
INSERT INTO product_catalog(name) VALUES('Wild plum (munydjudj)');
INSERT INTO product_catalog(name) VALUES('Wild plum');
INSERT INTO product_catalog(name) VALUES('Wild Mangosteen');
INSERT INTO product_catalog(name) VALUES('Rubus phoenicolasius');
INSERT INTO product_catalog(name) VALUES('Wolfberry');
INSERT INTO product_catalog(name) VALUES('Wongi');
INSERT INTO product_catalog(name) VALUES('Wood Apple');

INSERT INTO product_catalog(name) VALUES('Myrica rubra');
INSERT INTO product_catalog(name) VALUES('Yantok');
INSERT INTO product_catalog(name) VALUES('Yellow Granadilla');
INSERT INTO product_catalog(name) VALUES('Yellow Mombin');
INSERT INTO product_catalog(name) VALUES('Yellow plum');
INSERT INTO product_catalog(name) VALUES('Yew');
INSERT INTO product_catalog(name) VALUES('Youngberry');

INSERT INTO product_catalog(name) VALUES('Zig Zag Vine');
INSERT INTO product_catalog(name) VALUES('Jujube');
INSERT INTO product_catalog(name) VALUES('Zwetschge');

-- https://en.wikipedia.org/wiki/List_of_cakes
INSERT INTO product_catalog(name) VALUES('Angel cake');
INSERT INTO product_catalog(name) VALUES('Angel food cake');
INSERT INTO product_catalog(name) VALUES('Apple cake');
INSERT INTO product_catalog(name) VALUES('Aranygaluska');

INSERT INTO product_catalog(name) VALUES('Babka');
INSERT INTO product_catalog(name) VALUES('Ballokume');
INSERT INTO product_catalog(name) VALUES('Basbousa');
INSERT INTO product_catalog(name) VALUES('Better than sex cake');
INSERT INTO product_catalog(name) VALUES('Boston cream pie');
INSERT INTO product_catalog(name) VALUES('Banana cake/bread');
INSERT INTO product_catalog(name) VALUES('Banoffee pie');
INSERT INTO product_catalog(name) VALUES('Bara brith');
INSERT INTO product_catalog(name) VALUES('Battenberg cake');
INSERT INTO product_catalog(name) VALUES('Baumkuchen');
INSERT INTO product_catalog(name) VALUES('Bibingka');
INSERT INTO product_catalog(name) VALUES('Bienenstich');
INSERT INTO product_catalog(name) VALUES('Birthday cake');
INSERT INTO product_catalog(name) VALUES('Black Forest cake');
INSERT INTO product_catalog(name) VALUES('Blondie');
INSERT INTO product_catalog(name) VALUES('Brownie');
INSERT INTO product_catalog(name) VALUES('Buccellato');
INSERT INTO product_catalog(name) VALUES('Budapestlängd');
INSERT INTO product_catalog(name) VALUES('Bundt cake');
INSERT INTO product_catalog(name) VALUES('Butter cake');
INSERT INTO product_catalog(name) VALUES('Butterfly cake');

INSERT INTO product_catalog(name) VALUES('Cassata');
INSERT INTO product_catalog(name) VALUES('Carrot cake');
INSERT INTO product_catalog(name) VALUES('Cheesecake');
INSERT INTO product_catalog(name) VALUES('Chiffon cake');
INSERT INTO product_catalog(name) VALUES('Chocolate cake');
INSERT INTO product_catalog(name) VALUES('Christmas cake');
INSERT INTO product_catalog(name) VALUES('Cinco leches cake');

INSERT INTO product_catalog(name) VALUES('Coconut cake');

INSERT INTO product_catalog(name) VALUES('Coffee cake');
INSERT INTO product_catalog(name) VALUES('Cremeschnitte');
INSERT INTO product_catalog(name) VALUES('Croquembouche');
INSERT INTO product_catalog(name) VALUES('Crystal cake');
INSERT INTO product_catalog(name) VALUES('Cuatro leches cake');

INSERT INTO product_catalog(name) VALUES('Cupcake');
INSERT INTO product_catalog(name) VALUES('Dacquoise');
INSERT INTO product_catalog(name) VALUES('Date and walnut loaf');
INSERT INTO product_catalog(name) VALUES('Date square');
INSERT INTO product_catalog(name) VALUES('Depression cake');

INSERT INTO product_catalog(name) VALUES('Devil''s food cake');
INSERT INTO product_catalog(name) VALUES('Dobos cake');
INSERT INTO product_catalog(name) VALUES('Dundee cake');
INSERT INTO product_catalog(name) VALUES('Eccles cake');
INSERT INTO product_catalog(name) VALUES('Esterházy torte');
INSERT INTO product_catalog(name) VALUES('Fat rascal');
INSERT INTO product_catalog(name) VALUES('Faworki');
INSERT INTO product_catalog(name) VALUES('Financier');
INSERT INTO product_catalog(name) VALUES('Flourless chocolate cake');
INSERT INTO product_catalog(name) VALUES('Fondant Fancy');
INSERT INTO product_catalog(name) VALUES('Frog cake');
INSERT INTO product_catalog(name) VALUES('Fruitcake');
INSERT INTO product_catalog(name) VALUES('Funing big cake');

INSERT INTO product_catalog(name) VALUES('Genoa cake');
INSERT INTO product_catalog(name) VALUES('Genoise');
INSERT INTO product_catalog(name) VALUES('Gingerbread');
INSERT INTO product_catalog(name) VALUES('Gooey butter cake');
INSERT INTO product_catalog(name) VALUES('Goose Breast');

INSERT INTO product_catalog(name) VALUES('Hash brownies');
INSERT INTO product_catalog(name) VALUES('Hot milk cake');

INSERT INTO product_catalog(name) VALUES('Ice cream cake');

INSERT INTO product_catalog(name) VALUES('Jaffa Cakes');

INSERT INTO product_catalog(name) VALUES('Kabuni');
INSERT INTO product_catalog(name) VALUES('Karpatka');
INSERT INTO product_catalog(name) VALUES('Kiev cake');
INSERT INTO product_catalog(name) VALUES('King cake');
INSERT INTO product_catalog(name) VALUES('Kladdkaka');
INSERT INTO product_catalog(name) VALUES('Kli??eris');
INSERT INTO product_catalog(name) VALUES('Kolacz');
INSERT INTO product_catalog(name) VALUES('Kolaczki');
INSERT INTO product_catalog(name) VALUES('Kouign-amann');
INSERT INTO product_catalog(name) VALUES('Kutia');
INSERT INTO product_catalog(name) VALUES('Kransekake');
INSERT INTO product_catalog(name) VALUES('Kremówka');
INSERT INTO product_catalog(name) VALUES('Krowka');
INSERT INTO product_catalog(name) VALUES('Lady Baltimore Cake');

INSERT INTO product_catalog(name) VALUES('Lamanki');
INSERT INTO product_catalog(name) VALUES('Lamington');
INSERT INTO product_catalog(name) VALUES('Layer cake');
INSERT INTO product_catalog(name) VALUES('Lemon cake');

INSERT INTO product_catalog(name) VALUES('Madeira cake');
INSERT INTO product_catalog(name) VALUES('Makowiec');
INSERT INTO product_catalog(name) VALUES('Magdalena');
INSERT INTO product_catalog(name) VALUES('Mantecada');
INSERT INTO product_catalog(name) VALUES('Marble cake');
INSERT INTO product_catalog(name) VALUES('Mazurek');
INSERT INTO product_catalog(name) VALUES('Mille-feuille');
INSERT INTO product_catalog(name) VALUES('Molten chocolate cake');
INSERT INTO product_catalog(name) VALUES('Mooncake');
INSERT INTO product_catalog(name) VALUES('Muffin');

INSERT INTO product_catalog(name) VALUES('Napoleonshat');
INSERT INTO product_catalog(name) VALUES('Napeleonskake');
INSERT INTO product_catalog(name) VALUES('Nasturtium cake');

INSERT INTO product_catalog(name) VALUES('Oponki');
INSERT INTO product_catalog(name) VALUES('Opera cake');
INSERT INTO product_catalog(name) VALUES('Orange and polenta cake');

INSERT INTO product_catalog(name) VALUES('Paczki');
INSERT INTO product_catalog(name) VALUES('Pancake');
INSERT INTO product_catalog(name) VALUES('Panpepato');
INSERT INTO product_catalog(name) VALUES('Panettone');
INSERT INTO product_catalog(name) VALUES('Parkin');
INSERT INTO product_catalog(name) VALUES('Pavlova');
INSERT INTO product_catalog(name) VALUES('Petit Gâteau');
INSERT INTO product_catalog(name) VALUES('Petits fours');
INSERT INTO product_catalog(name) VALUES('Piernik');
INSERT INTO product_catalog(name) VALUES('Pineapple upside-down cake');
INSERT INTO product_catalog(name) VALUES('Plum cake');
INSERT INTO product_catalog(name) VALUES('Pound cake');
INSERT INTO product_catalog(name) VALUES('Princess Cake');
INSERT INTO product_catalog(name) VALUES('Prinzregententorte');
INSERT INTO product_catalog(name) VALUES('Pumpkin bread');
INSERT INTO product_catalog(name) VALUES('Punschkrapfen');

INSERT INTO product_catalog(name) VALUES('Queen Elizabeth cake');
INSERT INTO product_catalog(name) VALUES('Qumeshtore me pete');

INSERT INTO product_catalog(name) VALUES('Red bean cake');
INSERT INTO product_catalog(name) VALUES('Red velvet cake');
INSERT INTO product_catalog(name) VALUES('Rum cake');
INSERT INTO product_catalog(name) VALUES('Rum baba');
INSERT INTO product_catalog(name) VALUES('Ruske kape');

INSERT INTO product_catalog(name) VALUES('Sachertorte');
INSERT INTO product_catalog(name) VALUES('Šakotis');
INSERT INTO product_catalog(name) VALUES('Salzburger Nockerl');
INSERT INTO product_catalog(name) VALUES('Seis leches cake');
INSERT INTO product_catalog(name) VALUES('Sekacz');
INSERT INTO product_catalog(name) VALUES('Sernik');
INSERT INTO product_catalog(name) VALUES('Sesame seed cake');
INSERT INTO product_catalog(name) VALUES('Sfouf');
INSERT INTO product_catalog(name) VALUES('Simnel cake');
INSERT INTO product_catalog(name) VALUES('Smoked salmon cheesecake');
INSERT INTO product_catalog(name) VALUES('Smörgåstårta');
INSERT INTO product_catalog(name) VALUES('Snowball cake');
INSERT INTO product_catalog(name) VALUES('Snow skin mooncake');
INSERT INTO product_catalog(name) VALUES('Soufflé');
INSERT INTO product_catalog(name) VALUES('Spekkoek');
INSERT INTO product_catalog(name) VALUES('Spice cake');
INSERT INTO product_catalog(name) VALUES('Spit cake');
INSERT INTO product_catalog(name) VALUES('Sponge cake');
INSERT INTO product_catalog(name) VALUES('St. Honoré cake');
INSERT INTO product_catalog(name) VALUES('Stack cake');
INSERT INTO product_catalog(name) VALUES('Streuselkuchen');
INSERT INTO product_catalog(name) VALUES('Sultana and cherry cake');
INSERT INTO product_catalog(name) VALUES('Suncake');
INSERT INTO product_catalog(name) VALUES('Swiss roll');

INSERT INTO product_catalog(name) VALUES('Tarte Tatin');
INSERT INTO product_catalog(name) VALUES('Tea loaf');
INSERT INTO product_catalog(name) VALUES('Teacake');
INSERT INTO product_catalog(name) VALUES('Tiramisu');
INSERT INTO product_catalog(name) VALUES('Tompouce');
INSERT INTO product_catalog(name) VALUES('Torta Tre Monti');
INSERT INTO product_catalog(name) VALUES('Tres leches cake');
INSERT INTO product_catalog(name) VALUES('Tunis cake');
INSERT INTO product_catalog(name) VALUES('Træstammer');

INSERT INTO product_catalog(name) VALUES('Upside-down cake');

INSERT INTO product_catalog(name) VALUES('Victoria sponge cake');

INSERT INTO product_catalog(name) VALUES('Wedding cake');
INSERT INTO product_catalog(name) VALUES('Welsh cake');
INSERT INTO product_catalog(name) VALUES('Whoopie pies');
INSERT INTO product_catalog(name) VALUES('Wine cake');

-- https://en.wikipedia.org/wiki/List_of_chicken_dishes
INSERT INTO product_catalog(name) VALUES('Airline chicken');
INSERT INTO product_catalog(name) VALUES('Andong jjimdak');
INSERT INTO product_catalog(name) VALUES('Arroz con pollo');
INSERT INTO product_catalog(name) VALUES('Ayam bakar');
INSERT INTO product_catalog(name) VALUES('Ayam goreng');
INSERT INTO product_catalog(name) VALUES('Ayam taliwang');
INSERT INTO product_catalog(name) VALUES('Barbecue chicken');
INSERT INTO product_catalog(name) VALUES('Barberton chicken');
INSERT INTO product_catalog(name) VALUES('Bean Sprouts Chicken');
INSERT INTO product_catalog(name) VALUES('Biryani');
INSERT INTO product_catalog(name) VALUES('Bon bon chicken');
INSERT INTO product_catalog(name) VALUES('Bourbon chicken');
INSERT INTO product_catalog(name) VALUES('Brown stew chicken');
INSERT INTO product_catalog(name) VALUES('Bubur ayam');
INSERT INTO product_catalog(name) VALUES('Buffalo wing');
INSERT INTO product_catalog(name) VALUES('Buldak');
INSERT INTO product_catalog(name) VALUES('Butter chicken');
INSERT INTO product_catalog(name) VALUES('Cafreal');
INSERT INTO product_catalog(name) VALUES('Cashew chicken');
INSERT INTO product_catalog(name) VALUES('Chicken 65');
INSERT INTO product_catalog(name) VALUES('Chicken à la King');
INSERT INTO product_catalog(name) VALUES('Chicken and duck blood soup');
INSERT INTO product_catalog(name) VALUES('Chicken and dumplings');
INSERT INTO product_catalog(name) VALUES('Chicken and waffles');
INSERT INTO product_catalog(name) VALUES('Chicken balls');
INSERT INTO product_catalog(name) VALUES('Chicken bog');
INSERT INTO product_catalog(name) VALUES('Chicken Chettinad');
INSERT INTO product_catalog(name) VALUES('Chicken curry');
INSERT INTO product_catalog(name) VALUES('Chicken Divan');
INSERT INTO product_catalog(name) VALUES('Chicken fingers');
INSERT INTO product_catalog(name) VALUES('Chicken French');
INSERT INTO product_catalog(name) VALUES('Chicken fries');
INSERT INTO product_catalog(name) VALUES('Chicken karahi');
INSERT INTO product_catalog(name) VALUES('Chicken Kiev');
INSERT INTO product_catalog(name) VALUES('Chicken Lahori');
INSERT INTO product_catalog(name) VALUES('Chicken lollipop');
INSERT INTO product_catalog(name) VALUES('Chicken Marengo');
INSERT INTO product_catalog(name) VALUES('Chicken marsala');
INSERT INTO product_catalog(name) VALUES('Chicken Maryland');
INSERT INTO product_catalog(name) VALUES('Chicken mull');
INSERT INTO product_catalog(name) VALUES('Chicken nugget');
INSERT INTO product_catalog(name) VALUES('Chicken paprikash');
INSERT INTO product_catalog(name) VALUES('Chicken pie');
INSERT INTO product_catalog(name) VALUES('Chicken riggies');
INSERT INTO product_catalog(name) VALUES('Chicken salad');
INSERT INTO product_catalog(name) VALUES('Chicken soup');
INSERT INTO product_catalog(name) VALUES('Chicken tabaka');
INSERT INTO product_catalog(name) VALUES('Chicken tatsuta');
INSERT INTO product_catalog(name) VALUES('Chicken tikka');
INSERT INTO product_catalog(name) VALUES('Chicken tikka masala');
INSERT INTO product_catalog(name) VALUES('Chicken Vesuvio');
INSERT INTO product_catalog(name) VALUES('Chicken with chilies');
INSERT INTO product_catalog(name) VALUES('Chikuzenni');
INSERT INTO product_catalog(name) VALUES('Chilli chicken');
INSERT INTO product_catalog(name) VALUES('Chi-Mc');
INSERT INTO product_catalog(name) VALUES('Chinese chicken salad');
INSERT INTO product_catalog(name) VALUES('Claypot chicken rice');
INSERT INTO product_catalog(name) VALUES('Cock-a-leekie soup');
INSERT INTO product_catalog(name) VALUES('Coq au vin');
INSERT INTO product_catalog(name) VALUES('Cordon bleu');
INSERT INTO product_catalog(name) VALUES('Coronation chicken');
INSERT INTO product_catalog(name) VALUES('Country Captain');
INSERT INTO product_catalog(name) VALUES('Coxinha');
INSERT INTO product_catalog(name) VALUES('Crispy fried chicken');
INSERT INTO product_catalog(name) VALUES('Dak galbi');
INSERT INTO product_catalog(name) VALUES('Dakjuk');
INSERT INTO product_catalog(name) VALUES('Dapanji');
INSERT INTO product_catalog(name) VALUES('Dong''an chicken');
INSERT INTO product_catalog(name) VALUES('Double Down');
INSERT INTO product_catalog(name) VALUES('Dragon tiger phoenix');
INSERT INTO product_catalog(name) VALUES('Drunken chicken');
INSERT INTO product_catalog(name) VALUES('Engagement Chicken');
INSERT INTO product_catalog(name) VALUES('Flying Jacob');
INSERT INTO product_catalog(name) VALUES('Fried chicken');
INSERT INTO product_catalog(name) VALUES('Galinha à africana');
INSERT INTO product_catalog(name) VALUES('Galinha à portuguesa');
INSERT INTO product_catalog(name) VALUES('Galinhada');
INSERT INTO product_catalog(name) VALUES('Gallo en chicha');
INSERT INTO product_catalog(name) VALUES('General Tso''s chicken');
INSERT INTO product_catalog(name) VALUES('Gribenes');
INSERT INTO product_catalog(name) VALUES('Gulai Ayam');
INSERT INTO product_catalog(name) VALUES('Hainanese chicken rice');
INSERT INTO product_catalog(name) VALUES('Hawaiian haystack');
INSERT INTO product_catalog(name) VALUES('Hot chicken');
INSERT INTO product_catalog(name) VALUES('Inasal na manok');
INSERT INTO product_catalog(name) VALUES('Jambonneau');
INSERT INTO product_catalog(name) VALUES('Jerk chicken');
INSERT INTO product_catalog(name) VALUES('Jubilee chicken');
INSERT INTO product_catalog(name) VALUES('Kai yang');
INSERT INTO product_catalog(name) VALUES('Kedjenou');
INSERT INTO product_catalog(name) VALUES('Kelaguen');
INSERT INTO product_catalog(name) VALUES('Korean fried chicken');
INSERT INTO product_catalog(name) VALUES('Kori Rotti');
INSERT INTO product_catalog(name) VALUES('Kung Pao chicken');
INSERT INTO product_catalog(name) VALUES('Lemon chicken');
INSERT INTO product_catalog(name) VALUES('Lontong Cap Go Meh');
INSERT INTO product_catalog(name) VALUES('Mie ayam');
INSERT INTO product_catalog(name) VALUES('Moo goo gai pan');
INSERT INTO product_catalog(name) VALUES('Murgh Musallam');
INSERT INTO product_catalog(name) VALUES('Musakhan');
INSERT INTO product_catalog(name) VALUES('Nasi liwet');
INSERT INTO product_catalog(name) VALUES('Nasi tim');
INSERT INTO product_catalog(name) VALUES('Olivier salad');
INSERT INTO product_catalog(name) VALUES('Opor ayam');
INSERT INTO product_catalog(name) VALUES('Orange chicken');
INSERT INTO product_catalog(name) VALUES('Ostropel');
INSERT INTO product_catalog(name) VALUES('Parmigiana');
INSERT INTO product_catalog(name) VALUES('Pastilla');
INSERT INTO product_catalog(name) VALUES('Piccata');
INSERT INTO product_catalog(name) VALUES('Pinikpikan');
INSERT INTO product_catalog(name) VALUES('Plecing ayam');
INSERT INTO product_catalog(name) VALUES('Pollo a la Brasa');
INSERT INTO product_catalog(name) VALUES('Poularde Albufera');
INSERT INTO product_catalog(name) VALUES('Poulet au fromage');
INSERT INTO product_catalog(name) VALUES('Rendang ayam');
INSERT INTO product_catalog(name) VALUES('Rollatini');
INSERT INTO product_catalog(name) VALUES('Rotisserie chicken');
INSERT INTO product_catalog(name) VALUES('Sajji');
INSERT INTO product_catalog(name) VALUES('Saltimbocca');
INSERT INTO product_catalog(name) VALUES('Samgyetang');
INSERT INTO product_catalog(name) VALUES('Sanbeiji');
INSERT INTO product_catalog(name) VALUES('Satay');
INSERT INTO product_catalog(name) VALUES('Scaloppine');
INSERT INTO product_catalog(name) VALUES('Schnitzel');
INSERT INTO product_catalog(name) VALUES('Sesame chicken');
INSERT INTO product_catalog(name) VALUES('Shish taouk');
INSERT INTO product_catalog(name) VALUES('Snake bite chicken');
INSERT INTO product_catalog(name) VALUES('Soto ayam');
INSERT INTO product_catalog(name) VALUES('Soy sauce chicken');
INSERT INTO product_catalog(name) VALUES('Swiss Wing');
INSERT INTO product_catalog(name) VALUES('Tandoori chicken');
INSERT INTO product_catalog(name) VALUES('Tavuk gö?sü');
INSERT INTO product_catalog(name) VALUES('Tbeet');
INSERT INTO product_catalog(name) VALUES('Thalassery biryani');
INSERT INTO product_catalog(name) VALUES('Torikatsu');
INSERT INTO product_catalog(name) VALUES('Tsukune');
INSERT INTO product_catalog(name) VALUES('Waterzooi');
INSERT INTO product_catalog(name) VALUES('Wenchang chicken');
INSERT INTO product_catalog(name) VALUES('White cut chicken');
INSERT INTO product_catalog(name) VALUES('Wyngz');
INSERT INTO product_catalog(name) VALUES('Yakitori');
INSERT INTO product_catalog(name) VALUES('Yassa');

-- https://en.wikipedia.org/wiki/List_of_board_games
INSERT INTO product_catalog(name) VALUES('Abalone');
INSERT INTO product_catalog(name) VALUES('Agon');
INSERT INTO product_catalog(name) VALUES('Backgammon');
INSERT INTO product_catalog(name) VALUES('Battleship');
INSERT INTO product_catalog(name) VALUES('Blockade');
INSERT INTO product_catalog(name) VALUES('Blood Bowl');
INSERT INTO product_catalog(name) VALUES('Bul');
INSERT INTO product_catalog(name) VALUES('Camelot');
INSERT INTO product_catalog(name) VALUES('Checkers');
INSERT INTO product_catalog(name) VALUES('Chess');
INSERT INTO product_catalog(name) VALUES('Cross and Circle game');
INSERT INTO product_catalog(name) VALUES('Daldøs');
INSERT INTO product_catalog(name) VALUES('Downfall');
INSERT INTO product_catalog(name) VALUES('DVONN');
INSERT INTO product_catalog(name) VALUES('Fanorona');
INSERT INTO product_catalog(name) VALUES('Game of the Generals');
INSERT INTO product_catalog(name) VALUES('Ghosts');
INSERT INTO product_catalog(name) VALUES('Go');
INSERT INTO product_catalog(name) VALUES('Gipf');
INSERT INTO product_catalog(name) VALUES('Guess Who?');
INSERT INTO product_catalog(name) VALUES('Hare and Hounds');
INSERT INTO product_catalog(name) VALUES('Hex');
INSERT INTO product_catalog(name) VALUES('Hijara');
INSERT INTO product_catalog(name) VALUES('Isola');
INSERT INTO product_catalog(name) VALUES('Janggi (Korean Chess)');
INSERT INTO product_catalog(name) VALUES('Le Jeu de la Guerre');
INSERT INTO product_catalog(name) VALUES('Kalah');
INSERT INTO product_catalog(name) VALUES('Kamisado');
INSERT INTO product_catalog(name) VALUES('Liu po');
INSERT INTO product_catalog(name) VALUES('Lost Cities');
INSERT INTO product_catalog(name) VALUES('Mad Gab');
INSERT INTO product_catalog(name) VALUES('Master Mind');
INSERT INTO product_catalog(name) VALUES('Nine Men''s Morris');
INSERT INTO product_catalog(name) VALUES('Obsession');
INSERT INTO product_catalog(name) VALUES('Othello');
INSERT INTO product_catalog(name) VALUES('Patolli');
INSERT INTO product_catalog(name) VALUES('Plateau');
INSERT INTO product_catalog(name) VALUES('PÜNCT');
INSERT INTO product_catalog(name) VALUES('Quarto');
INSERT INTO product_catalog(name) VALUES('Rithmomachy');
INSERT INTO product_catalog(name) VALUES('Sáhkku');
INSERT INTO product_catalog(name) VALUES('Senet');
INSERT INTO product_catalog(name) VALUES('Shogi');
INSERT INTO product_catalog(name) VALUES('Space Hulk');
INSERT INTO product_catalog(name) VALUES('Stratego');
INSERT INTO product_catalog(name) VALUES('Sugoroku');
INSERT INTO product_catalog(name) VALUES('Tâb');
INSERT INTO product_catalog(name) VALUES('Tablut');
INSERT INTO product_catalog(name) VALUES('Tantrix');
INSERT INTO product_catalog(name) VALUES('Wari');
INSERT INTO product_catalog(name) VALUES('Xiangqi (Chinese chess)');
INSERT INTO product_catalog(name) VALUES('YINSH');
INSERT INTO product_catalog(name) VALUES('ZÈRTZ');
INSERT INTO product_catalog(name) VALUES('13 Dead End Drive');
INSERT INTO product_catalog(name) VALUES('1313 Dead End Drive');
INSERT INTO product_catalog(name) VALUES('American Megafauna');
INSERT INTO product_catalog(name) VALUES('Anti-Monopoly');
INSERT INTO product_catalog(name) VALUES('Attack!');
INSERT INTO product_catalog(name) VALUES('Axis & Allies');
INSERT INTO product_catalog(name) VALUES('Bang!');
INSERT INTO product_catalog(name) VALUES('Battle Sheep');
INSERT INTO product_catalog(name) VALUES('Betrayal at House on the Hill');
INSERT INTO product_catalog(name) VALUES('Blokus');
INSERT INTO product_catalog(name) VALUES('Blood Feud in New York');
INSERT INTO product_catalog(name) VALUES('Blue Max');
INSERT INTO product_catalog(name) VALUES('Bookchase');
INSERT INTO product_catalog(name) VALUES('Castle Risk');
INSERT INTO product_catalog(name) VALUES('Clue Jr.: Case of the Missing Pet');
INSERT INTO product_catalog(name) VALUES('Coppit');
INSERT INTO product_catalog(name) VALUES('Crash! The bankrupt game');
INSERT INTO product_catalog(name) VALUES('Diplomacy');
INSERT INTO product_catalog(name) VALUES('Djambi');
INSERT INTO product_catalog(name) VALUES('Doom: The Boardgame');
INSERT INTO product_catalog(name) VALUES('Eclipse');
INSERT INTO product_catalog(name) VALUES('Finance');
INSERT INTO product_catalog(name) VALUES('Ghettopoly');
INSERT INTO product_catalog(name) VALUES('The Great Train Robbery');
INSERT INTO product_catalog(name) VALUES('Heroscape');
INSERT INTO product_catalog(name) VALUES('Hey, That''s My Fish!');
INSERT INTO product_catalog(name) VALUES('Hotels');
INSERT INTO product_catalog(name) VALUES('Jenga');
INSERT INTO product_catalog(name) VALUES('Khet');
INSERT INTO product_catalog(name) VALUES('King of Tokyo');
INSERT INTO product_catalog(name) VALUES('King Oil');
INSERT INTO product_catalog(name) VALUES('Ludo');
INSERT INTO product_catalog(name) VALUES('Monopoly');
INSERT INTO product_catalog(name) VALUES('Monopoly Junior');
INSERT INTO product_catalog(name) VALUES('Poleconomy');
INSERT INTO product_catalog(name) VALUES('Risk');
INSERT INTO product_catalog(name) VALUES('Shadow Hunters');
INSERT INTO product_catalog(name) VALUES('Shogun/Samurai Swords');
INSERT INTO product_catalog(name) VALUES('Solarquest');
INSERT INTO product_catalog(name) VALUES('Spy Alley');
INSERT INTO product_catalog(name) VALUES('Star Wars Epic Duels');
INSERT INTO product_catalog(name) VALUES('Star Wars Tactics');
INSERT INTO product_catalog(name) VALUES('StarCraft: The Board Game');
INSERT INTO product_catalog(name) VALUES('Strange Synergy');
INSERT INTO product_catalog(name) VALUES('Summit');
INSERT INTO product_catalog(name) VALUES('TEG');
INSERT INTO product_catalog(name) VALUES('Titan');
INSERT INTO product_catalog(name) VALUES('Tsuro');
INSERT INTO product_catalog(name) VALUES('Tsuro of the Seas');
INSERT INTO product_catalog(name) VALUES('War on Terror');
INSERT INTO product_catalog(name) VALUES('Cartagena');
INSERT INTO product_catalog(name) VALUES('Chicken Cha Cha Cha');
INSERT INTO product_catalog(name) VALUES('Formula Dé');
INSERT INTO product_catalog(name) VALUES('Game of the Goose');
INSERT INTO product_catalog(name) VALUES('Hare and Tortoise');
INSERT INTO product_catalog(name) VALUES('Mississippi Queen');
INSERT INTO product_catalog(name) VALUES('Transformers');
INSERT INTO product_catalog(name) VALUES('18XX');
INSERT INTO product_catalog(name) VALUES('221B Baker Street');
INSERT INTO product_catalog(name) VALUES('30 Seconds');
INSERT INTO product_catalog(name) VALUES('About Time');
INSERT INTO product_catalog(name) VALUES('Acquire');
INSERT INTO product_catalog(name) VALUES('Acronymble');
INSERT INTO product_catalog(name) VALUES('Adel Verpflichtet');
INSERT INTO product_catalog(name) VALUES('Afrikan tähti');
INSERT INTO product_catalog(name) VALUES('Agricola');
INSERT INTO product_catalog(name) VALUES('Air Charter');
INSERT INTO product_catalog(name) VALUES('Aksharit');
INSERT INTO product_catalog(name) VALUES('Aladdin''s Dragons');
INSERT INTO product_catalog(name) VALUES('Alhambra');
INSERT INTO product_catalog(name) VALUES('Alias');
INSERT INTO product_catalog(name) VALUES('Amun-Re');
INSERT INTO product_catalog(name) VALUES('Arkham Horror');
INSERT INTO product_catalog(name) VALUES('Articulate!');
INSERT INTO product_catalog(name) VALUES('Ashta Chamma');
INSERT INTO product_catalog(name) VALUES('Auf Achse');
INSERT INTO product_catalog(name) VALUES('Australia');
INSERT INTO product_catalog(name) VALUES('Balderdash');
INSERT INTO product_catalog(name) VALUES('Barbarossa');
INSERT INTO product_catalog(name) VALUES('Bezzerwizzer');
INSERT INTO product_catalog(name) VALUES('Battlestar Galactica Board Game & Expansions');
INSERT INTO product_catalog(name) VALUES('Blankety Blank');
INSERT INTO product_catalog(name) VALUES('Blokus');
INSERT INTO product_catalog(name) VALUES('(This Game Is) Bonkers!');
INSERT INTO product_catalog(name) VALUES('Brain Chain');
INSERT INTO product_catalog(name) VALUES('Brainstorm');
INSERT INTO product_catalog(name) VALUES('Break the Safe');
INSERT INTO product_catalog(name) VALUES('Buccaneer');
INSERT INTO product_catalog(name) VALUES('Camel Up');
INSERT INTO product_catalog(name) VALUES('Can''t Stop');
INSERT INTO product_catalog(name) VALUES('Candy Land');
INSERT INTO product_catalog(name) VALUES('Capitol');
INSERT INTO product_catalog(name) VALUES('Carcassonne');
INSERT INTO product_catalog(name) VALUES('Careers');
INSERT INTO product_catalog(name) VALUES('Caribbean');
INSERT INTO product_catalog(name) VALUES('Cartagena');
INSERT INTO product_catalog(name) VALUES('Caylus');
INSERT INTO product_catalog(name) VALUES('Chromino');
INSERT INTO product_catalog(name) VALUES('CirKis');
INSERT INTO product_catalog(name) VALUES('Civilization');
INSERT INTO product_catalog(name) VALUES('Clans');
INSERT INTO product_catalog(name) VALUES('Clue/Cluedo');
INSERT INTO product_catalog(name) VALUES('Concept');
INSERT INTO product_catalog(name) VALUES('Conspiracy');
INSERT INTO product_catalog(name) VALUES('Cosmic Encounter');
INSERT INTO product_catalog(name) VALUES('Cranium');
INSERT INTO product_catalog(name) VALUES('Crosstrack');
INSERT INTO product_catalog(name) VALUES('Dark Tower');
INSERT INTO product_catalog(name) VALUES('Dead of Winter: A Cross Roads Game');
INSERT INTO product_catalog(name) VALUES('Diamant');
INSERT INTO product_catalog(name) VALUES('Dixit');
INSERT INTO product_catalog(name) VALUES('Domaine');
INSERT INTO product_catalog(name) VALUES('Dominion');
INSERT INTO product_catalog(name) VALUES('Don''t Miss The Boat');
INSERT INTO product_catalog(name) VALUES('Don''t Quote Me');
INSERT INTO product_catalog(name) VALUES('Dorn');
INSERT INTO product_catalog(name) VALUES('Drunter und Drüber');
INSERT INTO product_catalog(name) VALUES('Dune');
INSERT INTO product_catalog(name) VALUES('El Grande');
INSERT INTO product_catalog(name) VALUES('Elfenland');
INSERT INTO product_catalog(name) VALUES('Enchanted Forest');
INSERT INTO product_catalog(name) VALUES('English draughts');
INSERT INTO product_catalog(name) VALUES('Entdecker');
INSERT INTO product_catalog(name) VALUES('Escape from Atlantis');
INSERT INTO product_catalog(name) VALUES('Evo');
INSERT INTO product_catalog(name) VALUES('Farlander');
INSERT INTO product_catalog(name) VALUES('Figure It Out');
INSERT INTO product_catalog(name) VALUES('Fireball Island');
INSERT INTO product_catalog(name) VALUES('Focus');
INSERT INTO product_catalog(name) VALUES('Fresco');
INSERT INTO product_catalog(name) VALUES('GiftTRAP');
INSERT INTO product_catalog(name) VALUES('Giganten');
INSERT INTO product_catalog(name) VALUES('Girl Talk');
INSERT INTO product_catalog(name) VALUES('Go');
INSERT INTO product_catalog(name) VALUES('Great Train Robbery');
INSERT INTO product_catalog(name) VALUES('GridIron Master');
INSERT INTO product_catalog(name) VALUES('History of the World');
INSERT INTO product_catalog(name) VALUES('Husker Du?');
INSERT INTO product_catalog(name) VALUES('I''m the Boss!');
INSERT INTO product_catalog(name) VALUES('Imperial');
INSERT INTO product_catalog(name) VALUES('Indigo');
INSERT INTO product_catalog(name) VALUES('Ingenious');
INSERT INTO product_catalog(name) VALUES('Inkan aarre');
INSERT INTO product_catalog(name) VALUES('Java');
INSERT INTO product_catalog(name) VALUES('Journey through Europe');
INSERT INTO product_catalog(name) VALUES('Junta');
INSERT INTO product_catalog(name) VALUES('Kill Doctor Lucky');
INSERT INTO product_catalog(name) VALUES('Kingdoms');
INSERT INTO product_catalog(name) VALUES('Landslide');
INSERT INTO product_catalog(name) VALUES('Las Vegas');
INSERT INTO product_catalog(name) VALUES('Le Havre');
INSERT INTO product_catalog(name) VALUES('Life');
INSERT INTO product_catalog(name) VALUES('Logo Board Game');
INSERT INTO product_catalog(name) VALUES('The London Game');
INSERT INTO product_catalog(name) VALUES('Lords of Waterdeep');
INSERT INTO product_catalog(name) VALUES('Löwenherz');
INSERT INTO product_catalog(name) VALUES('Luck of the Draw');
INSERT INTO product_catalog(name) VALUES('Die Macher');
INSERT INTO product_catalog(name) VALUES('The Mad Magazine Game');
INSERT INTO product_catalog(name) VALUES('Mahjong');
INSERT INTO product_catalog(name) VALUES('Malefiz');
INSERT INTO product_catalog(name) VALUES('Mall Madness');
INSERT INTO product_catalog(name) VALUES('Manhattan');
INSERT INTO product_catalog(name) VALUES('Master Labyrinth');
INSERT INTO product_catalog(name) VALUES('Masterpiece');
INSERT INTO product_catalog(name) VALUES('Medici');
INSERT INTO product_catalog(name) VALUES('Medina');
INSERT INTO product_catalog(name) VALUES('Mensch ärgere dich nicht');
INSERT INTO product_catalog(name) VALUES('Merchant of Venus');
INSERT INTO product_catalog(name) VALUES('Mexica');
INSERT INTO product_catalog(name) VALUES('Mine a million');
INSERT INTO product_catalog(name) VALUES('Modern Art');
INSERT INTO product_catalog(name) VALUES('Niagara');
INSERT INTO product_catalog(name) VALUES('Okey');
INSERT INTO product_catalog(name) VALUES('Omega Virus');
INSERT INTO product_catalog(name) VALUES('Outrage!');
INSERT INTO product_catalog(name) VALUES('Pack & Stack');
INSERT INTO product_catalog(name) VALUES('Pandemic');
INSERT INTO product_catalog(name) VALUES('Parcheesi');
INSERT INTO product_catalog(name) VALUES('Parqués');
INSERT INTO product_catalog(name) VALUES('Pay Day');
INSERT INTO product_catalog(name) VALUES('Personal Preference');
INSERT INTO product_catalog(name) VALUES('Pictionary');
INSERT INTO product_catalog(name) VALUES('Pirate''s Cove');
INSERT INTO product_catalog(name) VALUES('Power Grid');
INSERT INTO product_catalog(name) VALUES('Primordial Soup');
INSERT INTO product_catalog(name) VALUES('Princes of Florence');
INSERT INTO product_catalog(name) VALUES('Puerto Rico');
INSERT INTO product_catalog(name) VALUES('Quoridor');
INSERT INTO product_catalog(name) VALUES('Qwirkle');
INSERT INTO product_catalog(name) VALUES('Ra');
INSERT INTO product_catalog(name) VALUES('Rail Baron');
INSERT INTO product_catalog(name) VALUES('Rappakalja');
INSERT INTO product_catalog(name) VALUES('Razzia');
INSERT INTO product_catalog(name) VALUES('The Really Nasty Horse Racing Game');
INSERT INTO product_catalog(name) VALUES('Ricochet Robots');
INSERT INTO product_catalog(name) VALUES('Rivers, Roads & Rails');
INSERT INTO product_catalog(name) VALUES('RoboRally');
INSERT INTO product_catalog(name) VALUES('Rummikub');
INSERT INTO product_catalog(name) VALUES('Rummoli');
INSERT INTO product_catalog(name) VALUES('Saint Petersburg');
INSERT INTO product_catalog(name) VALUES('Samurai');
INSERT INTO product_catalog(name) VALUES('San Marco');
INSERT INTO product_catalog(name) VALUES('Scattergories');
INSERT INTO product_catalog(name) VALUES('Scene It');
INSERT INTO product_catalog(name) VALUES('Scotland Yard');
INSERT INTO product_catalog(name) VALUES('Scoundrels of Skullport');
INSERT INTO product_catalog(name) VALUES('Scrabble');
INSERT INTO product_catalog(name) VALUES('Sequence');
INSERT INTO product_catalog(name) VALUES('The Settlers of Catan');
INSERT INTO product_catalog(name) VALUES('Shadows over Camelot');
INSERT INTO product_catalog(name) VALUES('Sherlock Holmes Consulting Detective');
INSERT INTO product_catalog(name) VALUES('Skirrid');
INSERT INTO product_catalog(name) VALUES('Small World');
INSERT INTO product_catalog(name) VALUES('Snakes and Ladders');
INSERT INTO product_catalog(name) VALUES('Sorry!');
INSERT INTO product_catalog(name) VALUES('Splendor');
INSERT INTO product_catalog(name) VALUES('Squatter');
INSERT INTO product_catalog(name) VALUES('Stock Ticker');
INSERT INTO product_catalog(name) VALUES('Super Quiz');
INSERT INTO product_catalog(name) VALUES('Taj Mahal');
INSERT INTO product_catalog(name) VALUES('Take It Easy');
INSERT INTO product_catalog(name) VALUES('Take Off!');
INSERT INTO product_catalog(name) VALUES('Terra Mystica');
INSERT INTO product_catalog(name) VALUES('Through the Desert');
INSERT INTO product_catalog(name) VALUES('Thurn and Taxis');
INSERT INTO product_catalog(name) VALUES('Ticket to Ride');
INSERT INTO product_catalog(name) VALUES('Tigris & Euphrates');
INSERT INTO product_catalog(name) VALUES('Tikal');
INSERT INTO product_catalog(name) VALUES('Timberland');
INSERT INTO product_catalog(name) VALUES('Time''s Up!');
INSERT INTO product_catalog(name) VALUES('Top Secret Spies');
INSERT INTO product_catalog(name) VALUES('Torres');
INSERT INTO product_catalog(name) VALUES('Totopoly');
INSERT INTO product_catalog(name) VALUES('Tracks to Telluride');
INSERT INTO product_catalog(name) VALUES('TransAmerica');
INSERT INTO product_catalog(name) VALUES('Trivial Pursuit');
INSERT INTO product_catalog(name) VALUES('Trouble');
INSERT INTO product_catalog(name) VALUES('Twilight Imperium');
INSERT INTO product_catalog(name) VALUES('Ubongo');
INSERT INTO product_catalog(name) VALUES('Upwords');
INSERT INTO product_catalog(name) VALUES('Vanished Planet');
INSERT INTO product_catalog(name) VALUES('Vinci');
INSERT INTO product_catalog(name) VALUES('Yahtzee');
INSERT INTO product_catalog(name) VALUES('Yut');
INSERT INTO product_catalog(name) VALUES('Zombies!!!');
INSERT INTO product_catalog(name) VALUES('Acquire');
INSERT INTO product_catalog(name) VALUES('Junta');
INSERT INTO product_catalog(name) VALUES('Kolejka');
INSERT INTO product_catalog(name) VALUES('København');
INSERT INTO product_catalog(name) VALUES('Monopoly');
INSERT INTO product_catalog(name) VALUES('Power Grid');
INSERT INTO product_catalog(name) VALUES('Risk');
INSERT INTO product_catalog(name) VALUES('Risk 2210 AD');
INSERT INTO product_catalog(name) VALUES('Sentinels of the Multiverse');
INSERT INTO product_catalog(name) VALUES('The Settlers of Catan');
INSERT INTO product_catalog(name) VALUES('Ticket to Ride');
INSERT INTO product_catalog(name) VALUES('Blockhead!');
INSERT INTO product_catalog(name) VALUES('Buckaroo');
INSERT INTO product_catalog(name) VALUES('Camp Granada');
INSERT INTO product_catalog(name) VALUES('Carrom');
INSERT INTO product_catalog(name) VALUES('Chapayev');
INSERT INTO product_catalog(name) VALUES('Crokinole');
INSERT INTO product_catalog(name) VALUES('Dart Wars');
INSERT INTO product_catalog(name) VALUES('Gnip Gnop');
INSERT INTO product_catalog(name) VALUES('Hungry Hungry Hippos');
INSERT INTO product_catalog(name) VALUES('Jenga');
INSERT INTO product_catalog(name) VALUES('Kerplunk');
INSERT INTO product_catalog(name) VALUES('Krazy Maze');
INSERT INTO product_catalog(name) VALUES('MagnetX');
INSERT INTO product_catalog(name) VALUES('Operation');
INSERT INTO product_catalog(name) VALUES('Perfection');
INSERT INTO product_catalog(name) VALUES('Polarity');
INSERT INTO product_catalog(name) VALUES('Subbuteo');
INSERT INTO product_catalog(name) VALUES('Twister');
INSERT INTO product_catalog(name) VALUES('Villa Paletti');
INSERT INTO product_catalog(name) VALUES('Candy Land');
INSERT INTO product_catalog(name) VALUES('Catan Junior');
INSERT INTO product_catalog(name) VALUES('Chicken Cha Cha Cha');
INSERT INTO product_catalog(name) VALUES('Don''t Break the Ice');
INSERT INTO product_catalog(name) VALUES('Don''t Wake Daddy');
INSERT INTO product_catalog(name) VALUES('Forbidden Bridge');
INSERT INTO product_catalog(name) VALUES('Hey Pa! There''s a Goat on the Roof');
INSERT INTO product_catalog(name) VALUES('Hi Ho! Cherry-O');
INSERT INTO product_catalog(name) VALUES('Hungry Hungry Hippos');
INSERT INTO product_catalog(name) VALUES('The Kids of Catan');
INSERT INTO product_catalog(name) VALUES('Ludo');
INSERT INTO product_catalog(name) VALUES('Mouse Trap');
INSERT INTO product_catalog(name) VALUES('Snakes and ladders (aka Chutes and Ladders)');
INSERT INTO product_catalog(name) VALUES('Sorry!');
INSERT INTO product_catalog(name) VALUES('Space Hop');
INSERT INTO product_catalog(name) VALUES('Uncle Wiggily');
INSERT INTO product_catalog(name) VALUES('Pandemic');
INSERT INTO product_catalog(name) VALUES('X-COM');
INSERT INTO product_catalog(name) VALUES('Flibbix');
INSERT INTO product_catalog(name) VALUES('Hanafuda');
INSERT INTO product_catalog(name) VALUES('Icehouse pieces');
INSERT INTO product_catalog(name) VALUES('Stonehenge');
