DROP TABLE stores;
CREATE TABLE stores (id INTEGER, name TEXT);

-- https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population
INSERT INTO stores(id, name) VALUES (1, 'New York City');
INSERT INTO stores(id, name) VALUES (2, 'Los Angeles');
INSERT INTO stores(id, name) VALUES (3, 'Chicago');
INSERT INTO stores(id, name) VALUES (4, 'Houston');
INSERT INTO stores(id, name) VALUES (5, 'Philadelphia');
INSERT INTO stores(id, name) VALUES (6, 'Phoenix');
INSERT INTO stores(id, name) VALUES (7, 'San Antonio');
INSERT INTO stores(id, name) VALUES (8, 'San Diego');
INSERT INTO stores(id, name) VALUES (9, 'Dallas');
INSERT INTO stores(id, name) VALUES (10, 'San Jose');
INSERT INTO stores(id, name) VALUES (11, 'Austin');
INSERT INTO stores(id, name) VALUES (12, 'Jacksonville');
INSERT INTO stores(id, name) VALUES (13, 'San Francisco');
INSERT INTO stores(id, name) VALUES (14, 'Indianapolis');
INSERT INTO stores(id, name) VALUES (15, 'Columbus');
INSERT INTO stores(id, name) VALUES (16, 'Fort Worth');
INSERT INTO stores(id, name) VALUES (17, 'Charlotte');
INSERT INTO stores(id, name) VALUES (18, 'Detroit');
INSERT INTO stores(id, name) VALUES (19, 'El Paso');
INSERT INTO stores(id, name) VALUES (20, 'Seattle');
INSERT INTO stores(id, name) VALUES (21, 'Denver');
INSERT INTO stores(id, name) VALUES (22, 'Washington');
INSERT INTO stores(id, name) VALUES (23, 'Memphis');
INSERT INTO stores(id, name) VALUES (24, 'Boston');
INSERT INTO stores(id, name) VALUES (25, 'Nashville');
INSERT INTO stores(id, name) VALUES (26, 'Baltimore');
INSERT INTO stores(id, name) VALUES (27, 'Oklahoma City');
INSERT INTO stores(id, name) VALUES (28, 'Portland');
INSERT INTO stores(id, name) VALUES (29, 'Las Vegas');
INSERT INTO stores(id, name) VALUES (30, 'Louisville');
INSERT INTO stores(id, name) VALUES (31, 'Milwaukee');
INSERT INTO stores(id, name) VALUES (32, 'Albuquerque');
INSERT INTO stores(id, name) VALUES (33, 'Tucson');
INSERT INTO stores(id, name) VALUES (34, 'Fresno');
INSERT INTO stores(id, name) VALUES (35, 'Sacramento');
INSERT INTO stores(id, name) VALUES (36, 'Long Beach');
INSERT INTO stores(id, name) VALUES (37, 'Kansas City');
INSERT INTO stores(id, name) VALUES (38, 'Mesa');
INSERT INTO stores(id, name) VALUES (39, 'Atlanta');
INSERT INTO stores(id, name) VALUES (40, 'Virginia Beach');
INSERT INTO stores(id, name) VALUES (41, 'Omaha');
INSERT INTO stores(id, name) VALUES (42, 'Colorado Springs');
INSERT INTO stores(id, name) VALUES (43, 'Raleigh');
INSERT INTO stores(id, name) VALUES (44, 'Miami');
INSERT INTO stores(id, name) VALUES (45, 'Oakland');
INSERT INTO stores(id, name) VALUES (46, 'Minneapolis');
INSERT INTO stores(id, name) VALUES (47, 'Tulsa');
INSERT INTO stores(id, name) VALUES (48, 'Cleveland');
INSERT INTO stores(id, name) VALUES (49, 'Wichita');
INSERT INTO stores(id, name) VALUES (50, 'New Orleans');
INSERT INTO stores(id, name) VALUES (51, 'Arlington');
INSERT INTO stores(id, name) VALUES (52, 'Bakersfield');
INSERT INTO stores(id, name) VALUES (53, 'Tampa');
INSERT INTO stores(id, name) VALUES (54, 'Aurora');
INSERT INTO stores(id, name) VALUES (55, 'Honolulu');
INSERT INTO stores(id, name) VALUES (56, 'Anaheim');
INSERT INTO stores(id, name) VALUES (57, 'Santa Ana');
INSERT INTO stores(id, name) VALUES (58, 'Corpus Christi');
INSERT INTO stores(id, name) VALUES (59, 'Riverside');
INSERT INTO stores(id, name) VALUES (60, 'St');
INSERT INTO stores(id, name) VALUES (61, 'Lexington');
INSERT INTO stores(id, name) VALUES (62, 'Pittsburgh');
INSERT INTO stores(id, name) VALUES (63, 'Stockton');
INSERT INTO stores(id, name) VALUES (64, 'Anchorage');
INSERT INTO stores(id, name) VALUES (65, 'Cincinnati');
INSERT INTO stores(id, name) VALUES (66, 'Saint Paul');
INSERT INTO stores(id, name) VALUES (67, 'Greensboro');
INSERT INTO stores(id, name) VALUES (68, 'Toledo');
INSERT INTO stores(id, name) VALUES (69, 'Newark');
INSERT INTO stores(id, name) VALUES (70, 'Plano');
INSERT INTO stores(id, name) VALUES (71, 'Henderson');
INSERT INTO stores(id, name) VALUES (72, 'Lincoln');
INSERT INTO stores(id, name) VALUES (73, 'Orlando');
INSERT INTO stores(id, name) VALUES (74, 'Jersey City');
INSERT INTO stores(id, name) VALUES (75, 'Chula Vista');
INSERT INTO stores(id, name) VALUES (76, 'Buffalo');
INSERT INTO stores(id, name) VALUES (77, 'Fort Wayne');
INSERT INTO stores(id, name) VALUES (78, 'Chandler');
INSERT INTO stores(id, name) VALUES (79, 'St');
INSERT INTO stores(id, name) VALUES (80, 'Laredo');
INSERT INTO stores(id, name) VALUES (81, 'Durham');
INSERT INTO stores(id, name) VALUES (82, 'Irvine');
INSERT INTO stores(id, name) VALUES (83, 'Madison');
INSERT INTO stores(id, name) VALUES (84, 'Norfolk');
INSERT INTO stores(id, name) VALUES (85, 'Lubbock');
INSERT INTO stores(id, name) VALUES (86, 'Gilbert');
INSERT INTO stores(id, name) VALUES (87, 'Winston');
INSERT INTO stores(id, name) VALUES (88, 'Glendale');
INSERT INTO stores(id, name) VALUES (89, 'Reno');
INSERT INTO stores(id, name) VALUES (90, 'Hialeah');
INSERT INTO stores(id, name) VALUES (91, 'Garland');
INSERT INTO stores(id, name) VALUES (92, 'Chesapeake');
INSERT INTO stores(id, name) VALUES (93, 'Irving');
INSERT INTO stores(id, name) VALUES (94, 'North Las Vegas');
INSERT INTO stores(id, name) VALUES (95, 'Scottsdale');
INSERT INTO stores(id, name) VALUES (96, 'Baton Rouge');
INSERT INTO stores(id, name) VALUES (97, 'Fremont');
INSERT INTO stores(id, name) VALUES (98, 'Richmond');
INSERT INTO stores(id, name) VALUES (99, 'Boise');
INSERT INTO stores(id, name) VALUES (100, 'San Bernardino');
INSERT INTO stores(id, name) VALUES (101, 'Birmingham');
INSERT INTO stores(id, name) VALUES (102, 'Spokane');
INSERT INTO stores(id, name) VALUES (103, 'Rochester');
INSERT INTO stores(id, name) VALUES (104, 'Modesto');
INSERT INTO stores(id, name) VALUES (105, 'Des Moines');
INSERT INTO stores(id, name) VALUES (106, 'Oxnard');
INSERT INTO stores(id, name) VALUES (107, 'Tacoma');
INSERT INTO stores(id, name) VALUES (108, 'Fontana');
INSERT INTO stores(id, name) VALUES (109, 'Fayetteville');
INSERT INTO stores(id, name) VALUES (110, 'Moreno Valley');
INSERT INTO stores(id, name) VALUES (111, 'Columbus');
INSERT INTO stores(id, name) VALUES (112, 'Huntington Beach');
INSERT INTO stores(id, name) VALUES (113, 'Yonkers');
INSERT INTO stores(id, name) VALUES (114, 'Montgomery');
INSERT INTO stores(id, name) VALUES (115, 'Aurora');
INSERT INTO stores(id, name) VALUES (116, 'Glendale');
INSERT INTO stores(id, name) VALUES (117, 'Shreveport');
INSERT INTO stores(id, name) VALUES (118, 'Akron');
INSERT INTO stores(id, name) VALUES (119, 'Little Rock');
INSERT INTO stores(id, name) VALUES (120, 'Amarillo');
INSERT INTO stores(id, name) VALUES (121, 'Augusta');
INSERT INTO stores(id, name) VALUES (122, 'Mobile');
INSERT INTO stores(id, name) VALUES (123, 'Grand Rapids');
INSERT INTO stores(id, name) VALUES (124, 'Salt Lake City');
INSERT INTO stores(id, name) VALUES (125, 'Huntsville');
INSERT INTO stores(id, name) VALUES (126, 'Tallahassee');
INSERT INTO stores(id, name) VALUES (127, 'Grand Prairie');
INSERT INTO stores(id, name) VALUES (128, 'Overland Park');
INSERT INTO stores(id, name) VALUES (129, 'Knoxville');
INSERT INTO stores(id, name) VALUES (130, 'Brownsville');
INSERT INTO stores(id, name) VALUES (131, 'Worcester');
INSERT INTO stores(id, name) VALUES (132, 'Newport News');
INSERT INTO stores(id, name) VALUES (133, 'Santa Clarita');
INSERT INTO stores(id, name) VALUES (134, 'Providence');
INSERT INTO stores(id, name) VALUES (135, 'Fort Lauderdale');
INSERT INTO stores(id, name) VALUES (136, 'Garden Grove');
INSERT INTO stores(id, name) VALUES (137, 'Oceanside');
INSERT INTO stores(id, name) VALUES (138, 'Rancho Cucamonga');
INSERT INTO stores(id, name) VALUES (139, 'Santa Rosa');
INSERT INTO stores(id, name) VALUES (140, 'Port St');
INSERT INTO stores(id, name) VALUES (141, 'Chattanooga');
INSERT INTO stores(id, name) VALUES (142, 'Tempe');
INSERT INTO stores(id, name) VALUES (143, 'Jackson');
INSERT INTO stores(id, name) VALUES (144, 'Cape Coral');
INSERT INTO stores(id, name) VALUES (145, 'Vancouver');
INSERT INTO stores(id, name) VALUES (146, 'Ontario');
INSERT INTO stores(id, name) VALUES (147, 'Sioux Falls');
INSERT INTO stores(id, name) VALUES (148, 'Peoria');
INSERT INTO stores(id, name) VALUES (149, 'Springfield');
INSERT INTO stores(id, name) VALUES (150, 'Pembroke Pines');
INSERT INTO stores(id, name) VALUES (151, 'Elk Grove');
INSERT INTO stores(id, name) VALUES (152, 'Salem');
INSERT INTO stores(id, name) VALUES (153, 'Corona');
INSERT INTO stores(id, name) VALUES (154, 'Lancaster');
INSERT INTO stores(id, name) VALUES (155, 'Eugene');
INSERT INTO stores(id, name) VALUES (156, 'Palmdale');
INSERT INTO stores(id, name) VALUES (157, 'McKinney');
INSERT INTO stores(id, name) VALUES (158, 'Salinas');
INSERT INTO stores(id, name) VALUES (159, 'Fort Collins');
INSERT INTO stores(id, name) VALUES (160, 'Cary');
INSERT INTO stores(id, name) VALUES (161, 'Hayward');
INSERT INTO stores(id, name) VALUES (162, 'Springfield');
INSERT INTO stores(id, name) VALUES (163, 'Pasadena');
INSERT INTO stores(id, name) VALUES (164, 'Macon');
INSERT INTO stores(id, name) VALUES (165, 'Pomona');
INSERT INTO stores(id, name) VALUES (166, 'Alexandria');
INSERT INTO stores(id, name) VALUES (167, 'Escondido');
INSERT INTO stores(id, name) VALUES (168, 'Sunnyvale');
INSERT INTO stores(id, name) VALUES (169, 'Lakewood');
INSERT INTO stores(id, name) VALUES (170, 'Kansas City');
INSERT INTO stores(id, name) VALUES (171, 'Rockford');
INSERT INTO stores(id, name) VALUES (172, 'Torrance');
INSERT INTO stores(id, name) VALUES (173, 'Hollywood');
INSERT INTO stores(id, name) VALUES (174, 'Joliet');
INSERT INTO stores(id, name) VALUES (175, 'Bridgeport');
INSERT INTO stores(id, name) VALUES (176, 'Clarksville');
INSERT INTO stores(id, name) VALUES (177, 'Paterson');
INSERT INTO stores(id, name) VALUES (178, 'Naperville');
INSERT INTO stores(id, name) VALUES (179, 'Frisco');
INSERT INTO stores(id, name) VALUES (180, 'Mesquite');
INSERT INTO stores(id, name) VALUES (181, 'Savannah');
INSERT INTO stores(id, name) VALUES (182, 'Syracuse');
INSERT INTO stores(id, name) VALUES (183, 'Dayton');
INSERT INTO stores(id, name) VALUES (184, 'Pasadena');
INSERT INTO stores(id, name) VALUES (185, 'Orange');
INSERT INTO stores(id, name) VALUES (186, 'Fullerton');
INSERT INTO stores(id, name) VALUES (187, 'McAllen');
INSERT INTO stores(id, name) VALUES (188, 'Killeen');
INSERT INTO stores(id, name) VALUES (189, 'Hampton');
INSERT INTO stores(id, name) VALUES (190, 'Bellevue');
INSERT INTO stores(id, name) VALUES (191, 'Warren');
INSERT INTO stores(id, name) VALUES (192, 'Miramar');
INSERT INTO stores(id, name) VALUES (193, 'West Valley City');
INSERT INTO stores(id, name) VALUES (194, 'Olathe');
INSERT INTO stores(id, name) VALUES (195, 'Columbia');
INSERT INTO stores(id, name) VALUES (196, 'Sterling Heights');
INSERT INTO stores(id, name) VALUES (197, 'Thornton');
INSERT INTO stores(id, name) VALUES (198, 'New Haven');
INSERT INTO stores(id, name) VALUES (199, 'Waco');
INSERT INTO stores(id, name) VALUES (200, 'Charleston');
INSERT INTO stores(id, name) VALUES (201, 'Thousand Oaks');
INSERT INTO stores(id, name) VALUES (202, 'Visalia');
INSERT INTO stores(id, name) VALUES (203, 'Cedar Rapids');
INSERT INTO stores(id, name) VALUES (204, 'Elizabeth');
INSERT INTO stores(id, name) VALUES (205, 'Roseville');
INSERT INTO stores(id, name) VALUES (206, 'Gainesville');
INSERT INTO stores(id, name) VALUES (207, 'Carrollton');
INSERT INTO stores(id, name) VALUES (208, 'Stamford');
INSERT INTO stores(id, name) VALUES (209, 'Denton');
INSERT INTO stores(id, name) VALUES (210, 'Midland');
INSERT INTO stores(id, name) VALUES (211, 'Coral Springs');
INSERT INTO stores(id, name) VALUES (212, 'Concord');
INSERT INTO stores(id, name) VALUES (213, 'Topeka');
INSERT INTO stores(id, name) VALUES (214, 'Simi Valley');
INSERT INTO stores(id, name) VALUES (215, 'Surprise');
INSERT INTO stores(id, name) VALUES (216, 'Lafayette');
INSERT INTO stores(id, name) VALUES (217, 'Kent');
INSERT INTO stores(id, name) VALUES (218, 'Hartford');
INSERT INTO stores(id, name) VALUES (219, 'Santa Clara');
INSERT INTO stores(id, name) VALUES (220, 'Victorville');
INSERT INTO stores(id, name) VALUES (221, 'Abilene');
INSERT INTO stores(id, name) VALUES (222, 'Murfreesboro');
INSERT INTO stores(id, name) VALUES (223, 'Evansville');
INSERT INTO stores(id, name) VALUES (224, 'Vallejo');
INSERT INTO stores(id, name) VALUES (225, 'Athens');
INSERT INTO stores(id, name) VALUES (226, 'Allentown');
INSERT INTO stores(id, name) VALUES (227, 'Berkeley');
INSERT INTO stores(id, name) VALUES (228, 'Norman');
INSERT INTO stores(id, name) VALUES (229, 'Ann Arbor');
INSERT INTO stores(id, name) VALUES (230, 'Beaumont');
INSERT INTO stores(id, name) VALUES (231, 'Independence');
INSERT INTO stores(id, name) VALUES (232, 'Columbia');
INSERT INTO stores(id, name) VALUES (233, 'Springfield');
INSERT INTO stores(id, name) VALUES (234, 'El Monte');
INSERT INTO stores(id, name) VALUES (235, 'Fargo');
INSERT INTO stores(id, name) VALUES (236, 'Peoria');
INSERT INTO stores(id, name) VALUES (237, 'Provo');
INSERT INTO stores(id, name) VALUES (238, 'Lansing');
INSERT INTO stores(id, name) VALUES (239, 'Odessa');
INSERT INTO stores(id, name) VALUES (240, 'Downey');
INSERT INTO stores(id, name) VALUES (241, 'Wilmington');
INSERT INTO stores(id, name) VALUES (242, 'Arvada');
INSERT INTO stores(id, name) VALUES (243, 'Costa Mesa');
INSERT INTO stores(id, name) VALUES (244, 'Round Rock');
INSERT INTO stores(id, name) VALUES (245, 'Carlsbad');
INSERT INTO stores(id, name) VALUES (246, 'Miami Gardens');
INSERT INTO stores(id, name) VALUES (247, 'Westminster');
INSERT INTO stores(id, name) VALUES (248, 'Inglewood');
INSERT INTO stores(id, name) VALUES (249, 'Rochester');
INSERT INTO stores(id, name) VALUES (250, 'Fairfield');
INSERT INTO stores(id, name) VALUES (251, 'Elgin');
INSERT INTO stores(id, name) VALUES (252, 'West Jordan');
INSERT INTO stores(id, name) VALUES (253, 'Clearwater');
INSERT INTO stores(id, name) VALUES (254, 'Manchester');
INSERT INTO stores(id, name) VALUES (255, 'Lowell');
INSERT INTO stores(id, name) VALUES (256, 'Gresham');
INSERT INTO stores(id, name) VALUES (257, 'Cambridge');
INSERT INTO stores(id, name) VALUES (258, 'Ventura');
INSERT INTO stores(id, name) VALUES (259, 'Temecula');
INSERT INTO stores(id, name) VALUES (260, 'Waterbury');
INSERT INTO stores(id, name) VALUES (261, 'Antioch');
INSERT INTO stores(id, name) VALUES (262, 'Billings');
INSERT INTO stores(id, name) VALUES (263, 'High Point');
INSERT INTO stores(id, name) VALUES (264, 'Richardson');
INSERT INTO stores(id, name) VALUES (265, 'Richmond');
INSERT INTO stores(id, name) VALUES (266, 'West Covina');
INSERT INTO stores(id, name) VALUES (267, 'Pueblo');
INSERT INTO stores(id, name) VALUES (268, 'Murrieta');
INSERT INTO stores(id, name) VALUES (269, 'Centennial');
INSERT INTO stores(id, name) VALUES (270, 'Norwalk');
INSERT INTO stores(id, name) VALUES (271, 'North Charleston');
INSERT INTO stores(id, name) VALUES (272, 'Everett');
INSERT INTO stores(id, name) VALUES (273, 'Pompano Beach');
INSERT INTO stores(id, name) VALUES (274, 'Daly City');
INSERT INTO stores(id, name) VALUES (275, 'Palm Bay');
INSERT INTO stores(id, name) VALUES (276, 'Burbank');
INSERT INTO stores(id, name) VALUES (277, 'Wichita Falls');
INSERT INTO stores(id, name) VALUES (278, 'Boulder');
INSERT INTO stores(id, name) VALUES (279, 'Green Bay');
INSERT INTO stores(id, name) VALUES (280, 'Broken Arrow');
INSERT INTO stores(id, name) VALUES (281, 'West Palm Beach');
INSERT INTO stores(id, name) VALUES (282, 'College Station');
INSERT INTO stores(id, name) VALUES (283, 'Pearland');
INSERT INTO stores(id, name) VALUES (284, 'Santa Maria');
INSERT INTO stores(id, name) VALUES (285, 'El Cajon');
INSERT INTO stores(id, name) VALUES (286, 'San Mateo');
INSERT INTO stores(id, name) VALUES (287, 'Lewisville');
INSERT INTO stores(id, name) VALUES (288, 'Rialto');
INSERT INTO stores(id, name) VALUES (289, 'Davenport');
INSERT INTO stores(id, name) VALUES (290, 'Lakeland');
INSERT INTO stores(id, name) VALUES (291, 'Clovis');
INSERT INTO stores(id, name) VALUES (292, 'Sandy Springs');
INSERT INTO stores(id, name) VALUES (293, 'Tyler');
INSERT INTO stores(id, name) VALUES (294, 'Las Cruces');
INSERT INTO stores(id, name) VALUES (295, 'South Bend');
